# ===================================================================
# CONFIGURACION DEL SERVIDOR
# ===================================================================
server.port=${PORT:8089}

# ===================================================================
# CONFIGURACION DE CREDENCIALES Y API DE SUPABASE
# ===================================================================
supabase.url=${SUPABASE_URL:https://gvmjjobeboymfsfjpkai.supabase.co}
supabase.secret-key=${SUPABASE_SECRET_KEY:}
supabase.publishable-key=${SUPABASE_PUBLISHABLE_KEY:}

# ===================================================================
# CONFIGURACION DE BASE DE DATOS (Supabase PostgreSQL)
# ===================================================================
spring.datasource.url=${DB_URL:jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER:org.postgresql.Driver}

# Configuracion de JPA / Hibernate para PostgreSQL
spring.jpa.database=POSTGRESQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
